### ISSUE TITLE
Server Error for Camaro Package

### ISSUE THREAD

**Issue by AlanBreck** [Rich-Harris/packd#33]
When I attempt to get a bundle of the npm package, _Camaro_, I get a server error. Here is the URL: https://bundle.run/camaro@2.2.2

...and here is the error returned:

```
Command failed: npm_config_cache=~/.npm /var/app/current/node_modules/.bin/npm install --production gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error: `gyp` failed with exit code: 1 gyp ERR! stack at ChildProcess.onCpExit (/var/app/current/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16) gyp ERR! stack at emitTwo (events.js:125:13) gyp ERR! stack at ChildProcess.emit (events.js:213:7) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12) gyp ERR! System Linux 4.9.32-15.41.amzn1.x86_64 gyp ERR! command "/opt/elasticbeanstalk/node-install/node-v8.1.4-linux-x64/bin/node" "/var/app/current/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" gyp ERR! cwd /var/app/current/.tmp/camaro@2.2.2/package gyp ERR! node -v v8.1.4 gyp ERR! node-gyp -v v3.6.2 gyp ERR! not ok npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! camaro@2.2.2 install: `node-gyp rebuild` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the camaro@2.2.2 install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! /tmp/.npm/_logs/2017-12-07T17_19_15_984Z-debug.log
```

**Comment by xtuc** [comment]
Yes indeed, but it seems that the error `Undefined variable module_name in binding.gyp` is not related to our service :thinking: 

I'm looking more in details, i'll let you know.

**Comment by xtuc** [comment]
Unfortunately Camaro is not working in browser environments (see https://github.com/tuananh/camaro/issues/21#issuecomment-350150607).

I'm closing this since it's not related to our service.
