### ISSUE TITLE
axs broken

### ISSUE THREAD

**Issue by lachlanjc** [Rich-Harris/packd#7]
[Axs](/jxnblk/axs) doesn't seem to be bundling properly: https://packd.now.sh/bundle/axs@1.0.6

**Comment by Rich-Harris** [comment]
Turns out this is an issue with axs, not packd — it depends on react, but react is incorrectly listed as a devDependency rather than as a dependency. The same failure occurs with wzrd.in: https://wzrd.in/standalone/axs@latest

I'm going to close this as it will need to be fixed by axs — thanks.

<details>
<summary>packd error log</summary>

```
packd info ::1 - - [Fri, 31 Mar 2017 14:58:19 GMT] "GET /bundle/axs@1.0.6 HTTP/1.1"
packd info [axs] requested package
packd info [axs] is not cached
packd info [axs] fetching https://registry.npmjs.org/axs/-/axs-1.0.6.tgz
packd info [axs] running yarn --production
packd info [axs] No ES2015 module found, using Browserify
packd error [axs] Cannot find module 'react' from '/tmp/axs@1.0.6/package/dist'
```
</details>

<details>
<summary>wzrn.in error log</summary>

```
---FLAGRANT SYSTEM ERROR---

(logs uuid: 6877b1c0-167c-11e7-939c-7182eee89600 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react' from '/tmp/axs11731-24276-lmsl6u/node_modules/axs/dist'
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

dirPath: /tmp/axs11731-24276-lmsl6u

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jfhbrook/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```
</details>
