### ISSUE TITLE
Server error for https://bundle.run/ase-utils@0.1.1

### ISSUE THREAD

**Issue by mootari** [Rich-Harris/packd#84]
https://bundle.run/ase-utils@0.1.1 could be accessed on July 22nd, and possibly after that.

When I tried to access it just now the following error was displayed:
```
Command failed: npm_config_cache=~/.npm /var/app/current/node_modules/.bin/npm install --production /var/app/current/node_modules/npm/node_modules/graceful-fs/polyfills.js:10 cwd = origCwd.call(process) ^ Error: ENOENT: no such file or directory, uv_cwd at process.cwd (/var/app/current/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19) at Object.resolve (path.js:1084:25) at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:478:17) at Function.Module._resolveFilename (internal/modules/cjs/loader.js:573:20) at Function.Module._load (internal/modules/cjs/loader.js:506:25) at Module.require (internal/modules/cjs/loader.js:636:17) at require (internal/modules/cjs/helpers.js:20:18) at /var/app/current/node_modules/npm/bin/npm-cli.js:29:17 at Object. (/var/app/current/node_modules/npm/bin/npm-cli.js:152:3) at Module._compile (internal/modules/cjs/loader.js:688:30)
```

Formatted output:
```
Command failed: npm_config_cache=~/.npm /var/app/current/node_modules/.bin/npm install --production /var/app/current/node_modules/npm/node_modules/graceful-fs/polyfills.js:10 cwd = origCwd.call(process)

^ Error: ENOENT: no such file or directory, uv_cwd
at process.cwd (/var/app/current/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
at Object.resolve (path.js:1084:25)
at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:478:17)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:573:20)
at Function.Module._load (internal/modules/cjs/loader.js:506:25)
at Module.require (internal/modules/cjs/loader.js:636:17)
at require (internal/modules/cjs/helpers.js:20:18)
at /var/app/current/node_modules/npm/bin/npm-cli.js:29:17
at Object. (/var/app/current/node_modules/npm/bin/npm-cli.js:152:3)
at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by mootari** [comment]
The error has disappeared.
